services:
  - type: worker
    name: antautosurf-render-test
    runtime: image
    image:
      url: renderbase/python-playwright:latest
    buildCommand: |
      pip install -r requirements.txt
      playwright install firefox
    startCommand: python antautosurf_render.py
