services:
  - type: worker
    name: antautosurf-render-test
    runtime: image
    repo: https://github.com/zenadazurli/antautosurf-render-test
    plan: free
    dockerfilePath: ./Dockerfile
